name: Ruby

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.4.3'
    services:
      postgres:
          image: postgres:alpine
          ports:
            - 5432:5432
          env:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
          options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      env:
        DATABASE_HOST: localhost
      run: bundle exec rake
